# Generated by Django 5.2.8 on 2025-11-29 05:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_generatemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenerateModel',
            new_name='GeneratedModel',
        ),
    ]
