# Generated by Django 5.2.8 on 2026-05-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_rename_generatemodel_generatedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmodel',
            name='task_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
