# Generated by Django 5.2.8 on 2026-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_generatedmodel_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmodel',
            name='image_token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
