# Generated by Django 5.2.8 on 2026-05-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0005_generatedmodel_image_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
