# Generated by Django 5.2.8 on 2026-05-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_credits_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
