# Generated by Django 5.2.8 on 2026-09-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
    ]
